export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // header and footer props
  const header = (
    <header>
      <div>
        <h1>dern.blog</h1>
        <p>
          Thanks for checking out the blog -- I write about Bitcoin,
          Regenerative Agriculture, and more 🤙
        </p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div>
        <br />
        <h3>Built by Bitdern</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <head />
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
